# Generated by Django 5.2.5 on 2025-08-19 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='primary_image',
            field=models.ImageField(blank=True, null=True, upload_to='assests/services/primary/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='secondary_image',
            field=models.ImageField(blank=True, null=True, upload_to='assests/services/secondary/'),
        ),
    ]
