# Generated by Django 5.2.5 on 2025-08-18 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_created_at_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emirate', models.CharField(blank=True, max_length=50, null=True)),
                ('city_or_area', models.CharField(blank=True, max_length=100, null=True)),
                ('street_or_road', models.CharField(blank=True, max_length=150, null=True)),
                ('building_name', models.CharField(blank=True, max_length=150, null=True)),
                ('apartment_no', models.CharField(blank=True, max_length=20, null=True)),
                ('post_box', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
