# Generated by Django 5.2.5 on 2025-08-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_schedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={},
        ),
        migrations.AddField(
            model_name='schedule',
            name='proposed_by',
            field=models.CharField(choices=[('client', 'Client'), ('provider', 'Service Provider')], default='client', max_length=20),
        ),
        migrations.AddField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
