# Generated by Django 5.2.5 on 2025-08-20 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_orderitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='service',
        ),
    ]
